spring:
  application:
    name: 'venda'
  datasource:
    username: root 
    password: 123456
    url: jdbc:mysql://localhost:3306/venda
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8084
  servlet:
    context-path: /venda
  